### ISSUE TITLE
JWT토큰 만료 시 500 에러 반환함

### ISSUE THREAD

**Issue by GuardJo** [KNU-CSE14/edio_backend#71]
JWT access token 기한 만료 시 AuthenticationException (edio꺼)을 던지나 결과적으로 500 Error로 반환됨

![Image](https://github.com/user-attachments/assets/8e87b704-7cb5-40b2-855d-c060492f7aae)
![Image](https://github.com/user-attachments/assets/e5685bbd-c0f3-4d42-ba58-99c0a669e653)

- [ ] 토큰 만료 시 401 에러 반환하도록 개선
- [ ] 테스트 및 배포

**Comment by GuardJo** [comment]
기한 지난 access-tokern
accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYWdoMTIxOEBnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiYWNjb3VudElkIjoxLCJleHAiOjE3MzQ3NzUyNTV9.VyjjTR9ArU1fwZqhHYOkyFk9D7_4Qmh7p55f3zY4PC0

**Comment by zz106603** [comment]
이 내용 인지하고 있어서 아마 지금 아직 PR만들지 않은 로컬에 작업은 되어있을텐데 확인해서 pr 내용에 포함시킬 예정이요

**Comment by GuardJo** [comment]
그럼 @zz106603 님께 해당 이슈 assign 드렸으니 develop 후 이슈 closed 부탁 드릴게요 🙏
